name: Docker Compose CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: |
          docker-compose build
          docker login --username deweiliu --password ${{ secrets.docker_access }}
          docker-compose push
          docker logout
